---
title: "Proposal"
---
## **Salaries Across Data Science Postings** 


### **TEAM** 

Team Member  Sohail Mohammed
Team Member Munyaradzi Masvaure

### **PROJECT DESCRIPTION**

The project aims to explore and statistically predict the relationship between salaries and other variables through data science approaches such as data cleaning, wrangling, visualizing, mapping and building shiny app to make it easy for viewers/users to see the effects of change in salary. 

### **RESEARCH QUESTION(S)**

1. “Exploring the relationship between salaries for data science job postings based on  factors such as seniority, job title, company type, employment location, and industry, and how they  relate to salary levels?”
2. Predicting with 99% confidence intervals the salary of the population of Data Science job postings in the world based on   factors such as seniority, job title, company type, employment location, and industry and how it affects salary levels? 
MOTIVATION AND INSPIRATION 
As potential/aspiring data scientists, we want to have a better understanding of the job market and build awareness of factors affecting salaries especially in the United States considering the current transformations and fast-changing job market. 
 

### **Data Set**
[Dataset](https://www.kaggle.com/datasets/nalisha/data-science-careers-and-salaries-2025)


### **Implementation Plan**

Dependent Variable: Salary (either as a numeric amount, or grouped categories if ranges/bands more common)
Independent Variables: Job title, seniority level, location, industry, company size, company ownership, employment status
Exploratory Steps:
Cleaning and wrangling data
Summarize salary distributions across job titles and seniority levels.​
Compare salaries by city and remote status.​
Assess influence of company size and industry.​
Use statistical modeling (e.g., regression)  and visualizations to identify significant predictors.
Using Confidence Intervals and ML models to explore relationships between predictors and our response variable (salary). 

#### **Division of roles** : 
Sohail : Data Wrangling, contribute shiny app, Stats ML contribution
Munya: Sf Visualizations, Interpretations and findings, Code, Presentation


